name: my first workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "my first github action"

      - name: list the files
        run: ls

      - name: Check the user
        run: who am i

      - name: read file
        run: cat README.md